name: "GitHub Action for Verifying Node Package Module Version"
description: "Verifies that a NPM package matches the current tag"
runs:
  using: "node20"
  main: "index.js"
inputs:
  versionFilePath:
    description: Path to a JSON file containing a root version field
    required: false
    default: ./package.json
